### ISSUE TITLE
Migrate expect scripts to maintained automation for Switch management

### ISSUE THREAD

**Issue by akrzos** [redhat-performance/quads#159]
Consume another open source project called NAPALM to do switch management.  Seems like a good way to abstract the switch/network resources here and have something that can plug and play different vendor's switches.

https://github.com/napalm-automation/napalm

It is a pip package and is already integrated with Ansible.

**Comment by sadsfae** [comment]
While this looks pretty neat we'd require like this to be in RPM or system package format to include it with QUADS.  The alternative is to consume the Python functionality itself into Quads library (like we're doing for power management / strips).  Pushing this to 1.1 milestone for now, but we're really looking to move to Ansible completely for network abstraction when that is ready.

**Comment by sadsfae** [comment]
We've moved completely away from expect scripts and are currently using pexpect for `1.1` current codebase / master branch.  Napalm looks cool but I think our next jump is going to be directly into the Python libraries that come out of Ansible-Networking that @radez and others are working on upstream.

That's covered in this issue here: https://github.com/redhat-performance/quads/issues/205
