### ISSUE TITLE
Reporting availability of nodes in future

### ISSUE THREAD

**Issue by SahilTikale** [redhat-performance/quads#194]
Currently each node holds schedules up-to some point of time in future.
We need a way to collect a short summary of all available nodes, preferably nodewise and reported from which day in future are they available for accepting new schedule.

**Comment by sadsfae** [comment]
Hey @SahilTikale have you looked at the `--date` feature?  This does this to an extent:

e.g.

`quads-cli --cloud-only cloud01` 
versus 
`quads-cli --cloud-only cloud01 --date "2018-12-22 22:00"`

Because QUADS has the notion of an availability or free cloud definition (marked `Default cloud:` when listing a node schedule) you can just use this to query what nodes and how many would be available at a certain day/time.

It gets a little trickier when you want to see ranges however, which I think `/opt/quads/bin/find-available.py` is aiming to solve however we don't yet support passing in dates which is part of https://github.com/redhat-performance/quads/issues/77 and probably something we'd tackle in the `1.1` release or later.

Ultimately `/opt/quads/bin/find-available.py` should really just become part of `quads-cli` as well since we're making some great progress already with moving everything into innate Python functions, object calls and methods of QUADS.

https://github.com/radez/quads/pull/4
https://github.com/radez/quads/pull/5
https://github.com/radez/quads/pull/6

To this end, our primary goal is to first move all the cron tools functionality into QUADS directly then we will round up the other ancillary tools like `/opt/quads/bin/find-available.py`

**Comment by sadsfae** [comment]
> To this end, our primary goal is to first move all the cron tools functionality into QUADS directly then we will round up the other ancillary tools like /opt/quads/bin/find-available.py

This goal has already been achieved.  Leaving this open to track fully folding `bin/find-available.py` into `bin/quads-cli`

**Comment by sadsfae** [comment]
This is now in place in the `1.1` or `master` branch via the `--ls-available` command.

https://github.com/redhat-performance/quads/commit/9a2dcebc7a131d8550b809bf3d07e50984c4502b

Further, `bin/find-available.py` tool is superseded by this functionality so we're closing this now.
