### ISSUE TITLE
RFE: Continue breaking out quads.py

### ISSUE THREAD

**Issue by jtaleric** [redhat-performance/quads#25]
Based on a conversation I had with @kambiz-aghaiepour here are my suggestions for yet another change for quads.py.

Currently QUADs.py is a huge python class that tackles many things. I would suggest breaking out the the following, to ease further development and allow a plugin model.

```
schedule.py - Which can live on its own since this is the bread and butter of Quads.. This contain all methods pertaining to QUADs schedule.

hosts.py - Anything interacting with the hosts is done here.

clouds.py - Anything interacting with the clouds is done here. Clouds are made up of Host objects, I would think.

tickets.py - Class to define a ticketing system.
    |
rt.py - Inherits tickets to build the RT ticketing system plugin.

provisioner.py - Class to define provisioning systems.
     |
foreman.py - inherits provisioner to build the Foreman provisioning plugin

tools.py -  House methods that can / should be shared across all these above classes.
```

I also recommended getting rid of all the bash scripts so you can easily switch out hammer for some other tool to execute a like command, ie beaker.

I would also recommend moving the code base into a lib/ instead of bin/ -- You can create a bin/quads.py that imports the quads lib, imports the config and executes the main method.

**Comment by sadsfae** [comment]
@jtaleric thank you for the suggestions, we're always welcome to improvements in design and structure.  We'll chip away at this, possibly breaking them up into smaller pieces (we want to avoid large changesets for obvious reasons).

**Comment by jtaleric** [comment]
Sounds good will, please keep this issue updated so I can track it here. I will discuss further ideas with @kambiz-aghaiepour.

**Comment by jtaleric** [comment]
@kambiz-aghaiepour Further more, I would break out the expect script https://github.com/redhat-performance/quads/blob/master/bin/juniper-set-port.exp and convert that to pyexpect. Also, I would use the same methodology above for this.

Ie create a networking.py, and then a juniper.py which inherits networking.py.

**Comment by sadsfae** [comment]
> I would also recommend moving the code base into a lib/ instead of bin/ -- You can create a bin/quads.py that imports the quads lib, imports the config and executes the main method.

This part is completed.  We are keeping this open and are chipping away at it.

**Comment by sadsfae** [comment]
A lot of things have changed since this was last filed, I don't think it's relevant any longer and most of the ideas behind this have been implemented.

I think a better place to watch the more pythonic enhancements is going to be these RFE here:

https://github.com/redhat-performance/quads/issues/140
https://github.com/redhat-performance/quads/issues/156

Above, we're going to see a full move from a legacy API built around SimpleHTTPServer and a move into [CherryPy.](https://cherrypy.org/)

We'll also see a new API that's fully RESTful put in place and lastly a move away from manipulating locking, reads and writes of flat files into a proper ODM with [mongo documents.](https://docs.mongodb.com/manual/core/document/)
