### ISSUE TITLE
[RFE] extend --ls-available to allow for exclusions or subset searches

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#323]
When running ls-available, we should have a way to exclude current (specific) clouds, either for specific timeframes, or indefinitely, and we should also be able to look for specific host types.  This will be easily extensible once we have the host meta-data in place as well.

For example:

Currently we can do:

 quads-cli --ls-available --schedule-start "2020-03-10 01:45" --schedule-end "2020-03-22 22:00"

Possible example use cases:

exclude cloud03 when considering certain date ranges:

 quads-cli --ls-available --schedule-start "2020-03-10 01:45" --schedule-end "2020-03-22 22:00" --exclude "cloud03:2020-03-10 01:45:2020-03-22 22:00"

exclude cloud03 for a specific time range, and cloud05 for another time range:

quads-cli --ls-available --schedule-start "2020-03-10 01:45" --schedule-end "2020-03-22 22:00" --exclude "cloud03:2020-03-10 01:45:2020-03-22 22:00,cloud05:2020-03-10 01:45:2020-03-15 22:00"

(this is an example and can be done smarter if someone has a better idea)

exclude cloud03 for a specific time range, and cloud05 for full exclusion:

quads-cli --ls-available --schedule-start "2020-03-10 01:45" --schedule-end "2020-03-22 22:00" --exclude "cloud03:2020-03-10 01:45:2020-03-22 22:00,cloud05"

Additionally it would be nice to be able to limit the search results to specific host types, e.g.

quads-cli --ls-available --schedule-start "2020-03-10 01:45" --schedule-end "2020-03-22 22:00"  --limit r630,fc640

The latter can be done via pipes and taking the output and searching using grep, however it would be nice if the tool could limit results for us.  With host metadata we can do further limiting once we can add data to hosts.  For example being able to differentiate between differing models of 1029u hosts.

**Comment by grafuls** [comment]
The limit functionality has been implemented as `--filter` in [1].
Not sure I understand what you are trying to achieve with `--exclude` though. 
`--ls-available` implies we are showing available hosts (hosts which are not on any cloud during that time frame). 
Even if the point here is to assume we could finish some existing cloud assignments before their expiry date so that we can fulfill some more important requests, I don't think it would be necessary to include the date range on that exclude which seems overly complicated syntax for a regular user to make good use of.

[1] https://review.gerrithub.io/c/redhat-performance/quads/+/494554

**Comment by sadsfae** [comment]
I think we can close this out as it's implemented in the metadata RFE very recently as @grafuls points out:

https://github.com/redhat-performance/quads/commit/8c4c995d396649aab5f73bc0a3b34b2fa2742d0f
