### ISSUE TITLE
Reservation Lock and --find-free-cloud seeing all clouds as recently redefined?

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#349]
We're seeing some strange behavior on a recently updated QUADS `quads-1.1.4-20201119.noarch` (pre-1.1.4) with all of the clouds that should be free returning with a 48hr extension lock.

```
[root@quads11 ~]# quads-cli --find-free-cloud                                                                         
cloud17 (reserved: 47hr 59min remaining)
cloud18 (reserved: 47hr 59min remaining)
cloud19 (reserved: 47hr 59min remaining)
cloud20 (reserved: 47hr 59min remaining)
cloud21 (reserved: 47hr 59min remaining)
cloud22 (reserved: 47hr 59min remaining)
cloud23 (reserved: 47hr 59min remaining)
cloud24 (reserved: 47hr 59min remaining)
cloud25 (reserved: 47hr 59min remaining)
cloud26 (reserved: 47hr 59min remaining)
cloud27 (reserved: 47hr 59min remaining)
cloud28 (reserved: 47hr 59min remaining)
cloud29 (reserved: 47hr 59min remaining)
cloud30 (reserved: 47hr 59min remaining)
```

```
[root@quads11 ~]# quads --define-cloud cloud17 --description "Test-Cloudlock" --force --cloud-owner cenright --cloud-ticket 256
Can't redefine cloud:
cloud17 (reserved: 47hr 59min remaining)
```

The behavior we expect is that we shouldn't see reservation locks on anything that was not recently defined, but this could also be because MongoDB sees the new functinonality added to support reservation locks incorrectly as that all the clouds were recently redefined?

**Comment by sadsfae** [comment]
We'll report back to see if the reservation lock timeout counts down, if it does it could just be an artifact from the MongoDB schema/collection being updated the first time to support reservation lock feature.

**Comment by QuantumPosix** [comment]
Just checked, initially started to watch it at 11:36am EST and at 8:40pm EST the time still says cloud18 (reserved: 47hr 59min remaining)

**Comment by QuantumPosix** [comment]
Again ran the command this morning @6:09 EST:
cloud18 (reserved: 47hr 59min remaining)
Seems to be a bug with the lock with the first time setup of quads and
clouds.
~ Thanks,

Chris

**Comment by grafuls** [comment]
This is due to the default return value of `datetime.now()` set on https://github.com/redhat-performance/quads/blob/master/quads/model.py#L105 for last_redefined.
This only occurs due to the fact that those `clouds` which have an empty value under the last_redefined field are in fact returning the default value of `datetime.now()` after every execution. This would not happen on a fresh install of `Quads` and it's a direct consequence of the upgrade. This can also be worked around by populating that field with a past date value like `datetime.now()-timedelta(hours=48)`.
Closing this as not an issue on fresh deployments of `Quads`.

**Comment by sadsfae** [comment]
Workaround if this happens via Python interpreter:

```
>>> from quads.model import Cloud
>>> from datetime import datetime, timedelta
>>> clouds = Cloud.objects(last_redefined=None)
>>> for cloud in clouds:
...     cloud.update(last_redefined=datetime.now()-timedelta(hours=49))
```
