### ISSUE TITLE
[BUG] Cloud is not set to provisioned=True if schedule is removed while move is in progress

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/quads#361]
**Describe the bug**
There is a chance we might want to remove a schedule for a host moving into a new cloud while the move is still in progress. 
E.g.: All hosts on that cloud have already moved but 1 host is failing on the move step due to lack of network connectivity or broken state. If the schedule is removed, Quads has no chance to mark the cloud as provisioned=True due to the fact that the M&R action was not completed successfully.
The consequence of this is that the cloud will never go into validation 

**To Reproduce**
0. disable all crons
1. create new schedule for several hosts
2. setup one of those hosts to fail on move and rebuild (SSH disabled)
3. run M&R and have it move all host to the new cloud while failing on the one setup for fail
4. once the failed host is the only one left to move, remove the schedule for that host
5. run validate_env and notice no clouds are available for validation

**Expected behavior**
Cloud should go into validation despite host schedule being removed.

**Comment by sadsfae** [comment]
Closing this, not sure we've seen this for a few years now and we've been in this scenario a few times already.

**Comment by sadsfae** [comment]
This can be worked around by updating the `provisioned` boolean for `assignments` in Postgres for the affected assignment.

```
quads=# update assignments set provisioned = true where id = 54;
UPDATE 1
```

Documented here:  https://github.com/redhat-performance/quads?tab=readme-ov-file#validating-after-removing-hosts

**Comment by sadsfae** [comment]
It may originate here:  https://github.com/redhat-performance/quads/blob/latest/src/quads/tools/validate_env.py#L300 with `assignment = quads.get_active_cloud_assignment(self.cloud)` in the `validate_env` method and then later here I think a newly added host that's been swapped in will lead to the assignment (all hosts being validated) not meeting this `try`:   https://github.com/redhat-performance/quads/blob/latest/src/quads/tools/validate_env.py#L338 `quads.update_assignment(self.assignment.id, {"validated": True})` because it's individual validated host flag isn't set and doesn't match, and assignment validation is based on the sum of the parts of host validation.

Just guessing though.   We'll need to test.
