### ISSUE TITLE
[RFE] Make jira_watchers attempt to map submitter/cc-users to watchers

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#407]
This RFE covers attempting to make `jira_watchers.py` successfully map the requestor and any cc-users to watchers on JIRA ticket submission.

In the case we cannot successfully map requestor and cc-users to JIRA watchers we might include a one-time notification we send to the requestor email (cc'ing the `report_cc` users) with something like:

```
Thanks for submitting extension ticket $JIRA_TICKET_URL for environment $CLOUD.
Unfortunately we were unable to add you as a "watcher" to your newly created request.

Please navigate to  $JIRA_TICKET_URL and click on "Start watching this Issue" on the right-hand corner 
of the ticket screen to be apprised of updates and status changes to your request.
```

Related-to:  #350

**Comment by grafuls** [comment]
jira_watchers looks only for pending tickets with EXTENSION labels and if any of those have a parent jira ticket then we extract the watchers from it and include them into the extension ticket.
The functionality described is more suitable for the landing page to attempt to add the one submitting and those on cc users field as watchers on the main request ticket, so that when running jira_watchers we inherit all the necessary users.
Additionally if the mapping of cc user email to Jira is not accurate we can display that warning message on the "Thank you" page without limiting the ticket creation.
