### ISSUE TITLE
Populate per-port bandwidth graphing during assignments

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#85]
Currently we have a stub in the wiki generation for each host called graph.  This was left in place to late come through and add collectd-snmp port utilization and bandwidth metrics which would point to Grafana graphs for each host.

We would need to have dashboards automatically generated for all interfaces for each unique cloud assignment and owner.  Retention can be set on the Graphite side.

![screenshot_2017-05-12_15-44-12](https://cloud.githubusercontent.com/assets/3940978/26003262/163d5152-372a-11e7-890c-e41687f6d5e6.png)

**Comment by bengland2** [comment]
what about having a link to a graph of bandwidth on uplinks for each [rack entry here](http://wiki.scalelab.redhat.com/) next to each rack's name (e.g. "Rack 08").   This would be simpler to measure and would be useful for troubleshooting "noisy neighbor" network problems - since we can easily determine who we are sharing a rack with.   Joe's ideas for measuring network throughput of a cloud is a good one but I suspect it will be a while before we get to it, and knowing the cloud throughput doesn't necessarily mean you know whether a particular rack is overloading or not.

**Comment by sadsfae** [comment]
Related-to:  https://github.com/redhat-performance/quads/issues/228

**Comment by sadsfae** [comment]
We are now populating per-cloud bandwidth and power usage within Grafana (outside of QUADS).  I will leave this open and move it to 2.0 roadmap for implementing an optional place for wiki generation to include it for people that have similar setups.

**Comment by sadsfae** [comment]
Closing this issue, it's quite old and it also arguably extends farther than we can maintain into third-party platform support.
