### ISSUE TITLE
RFE: Add option for alternate inventory collection

### ISSUE THREAD

**Issue by QuantumPosix** [redhat-performance/quads#95]
Add an option in to use Ansible to collect machine information to auto generate wiki documentation.

This might be in the form of a variable called ```inventory_backend: ansible``` within the ```conf/quads.yml``` file.

Overall Idea:

- Use Ansible facts to generate infrastructure asset information (like Foreman does)
- Combine this with information about QUADS schedules
- Generate the appropriate markdown format for inclusion into Wordpress

**Comment by sadsfae** [comment]
I know it's been a while since this was opened but some things have changed.


> Add an option in to use Ansible to collect machine information to auto generate wiki documentation.
> 

No longer needed in `1.1`, we don't scrape anything anymore, it's all done via Python in single process here:  

https://github.com/redhat-performance/quads/blob/master/quads/tools/create_input.py
https://github.com/redhat-performance/quads/blob/master/quads/tools/create_input_assignments.py

> This might be in the form of a variable called `inventory_backend: ansible` within the `conf/quads.yml` file.

This might still be useful for sandbox testing, CI etc but then again there's been some work in containerizing Foreman for these sorts of things anyway.

I think that we can close this issue due to the main reasoning for it being providing a way to have hosts that can't be Foreman-managed still get their wiki and docs auto-generated/updated (This was the case with BAGL if I recall).

We can always revisit otherwise.

> 
> Overall Idea:
> 
>     * Use Ansible facts to generate infrastructure asset information (like Foreman does)
> 
>     * Combine this with information about QUADS schedules
> 
>     * Generate the appropriate markdown format for inclusion into Wordpress
