### ISSUE TITLE
Document How to make QUADS work for you

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/quads#96]
The current documentation is great. However there are a few missing gaps. It would  be great if we had a How to make QUADS work for you section where we go through the process how you would get started with using QUADS to manage your resources, for example defining hosts, setting up provisioning backend like foreman etc. If we can consolidate all the changes/procedures that one must go through like creating a machine to switch port mapping file etc, it would help anyone gauge the amount of work that they need to put in to adopt QUADS in their infrastructure.

**Comment by smalleni** [comment]
https://github.com/redhat-performance/quads/issues/94 is related.

**Comment by sadsfae** [comment]
Thanks for filing this, I think we have a good entry point here: https://github.com/redhat-performance/quads#quads-usage-documentation

This is where we planned on integrating a more full-blown ```getting started``` set of documentation like issue #94 

I'm going to mark this for the 1.0 milestone as well because frankly something isn't complete unless it's entirely documented :)
